### ISSUE TITLE
[BUG] EvictedCount is always 0

### ISSUE THREAD

**Issue by awlx** [maypok86/otter#108]
## Description

Maybe I am doing it wrong, but EvictedCount is always 0 in my tests, while all other counters work.

## To Reproduce
```
cache, err := otter.MustBuilder[string, model.Counters](100 * 1024 * 1024).
			CollectStats().
			Cost(func(key string, value model.Counters) uint32 {
				return uint32(len(key) + int(unsafe.Sizeof(value)))
			}).
			WithTTL(time.Minute * 5).
			Build()
```
## Expected behavior

evicted Counter counts up.

## Environment

- OS: golang 1.23 Ubuntu 24.04

**Comment by maypok86** [comment]
Hi, I would really appreciate it if you would provide some kind of test case, because otter passes, for example, such a test.
```go
func TestCache_Cost(t *testing.T) {
	size := getRandomSize(t)
	n := 1024
	var mutex sync.Mutex
	m := make(map[DeletionCause]int)
	c, err := MustBuilder[string, string](size * 1024 * n).
		CollectStats().
		WithTTL(5 * time.Minute).
		Cost(func(key string, value string) uint32 {
			return uint32(n)
		}).
		DeletionListener(func(key string, value string, cause DeletionCause) {
			mutex.Lock()
			m[cause]++
			mutex.Unlock()
		}).
		Build()
	if err != nil {
		t.Fatalf("can not create cache: %v", err)
	}

	iters := 1100 * size
	u := make(map[string]bool)
	for i := 0; i < iters; i++ {
		s := strconv.Itoa(i)
		u[s] = true
		c.Set(s, s)
	}

	mutex.Lock()
	defer mutex.Unlock()
	t.Logf("evicted: %d", m[Size])
	t.Logf("map size: %d", c.Size())
	t.Logf("iters: %d", iters)
	t.Logf("unique elements: %d", len(u))
	if len(m) != 1 || m[Size] <= 0 {
		t.Fatalf("cache was supposed to evict positive number of entries, but evicted %d entries", m[Size])
	}
	if c.Stats().EvictedCount() != int64(m[Size]) {
		t.Fatalf(
			"the EvictedCount should be equal to the number of Size causes of deletion. EvictedCount: %d, Size causes: %d",
			c.Stats().EvictedCount(),
			m[Size],
		)
	}
}
```

I can guess two possible reasons:
1. The cache never exceeds the maximum size.
2. All entries are expired. When I wrote the statistics, I did not consider expiration to be part of the eviction, which is perhaps not obvious. If you really need it, then you can either add a counter to the `DeletionListener`, or I can add a count of evicted entries for expiration as well.

**Comment by awlx** [comment]
Ah, I think the 2. case is the issue. I expected it to count up on expiry. So yes, it would be neat to also count up on expiry. The hint with the `DeletionListener` is also a good one so in the meanwhile I can add a counter there. Maybe it's even better to have an `ExpiredCount`. 

Thanks for the clarification much appreciated.

**Comment by maypok86** [comment]
I have published a new [release](https://github.com/maypok86/otter/releases/tag/v1.2.3) that should fix this bug.

**Comment by awlx** [comment]
Awesome thank you, I test it right away!

**Comment by awlx** [comment]
Perfect it works, I close this now. Much appreciated!

**Comment by maypok86** [comment]
@suederade This is very strange, especially considering that otter has quite a few different tests for this.

For example, otter passes the following test.
```go
func TestExtension_GetEntry(t *testing.T) {
	size := getRandomSize(t)
	defaultTTL := 2 * time.Second
	c, err := MustBuilder[int, int](size).
		WithTTL(defaultTTL).
		Build()
	if err != nil {
		t.Fatalf("cannot create builder: %v", err)
	}

	for i := 0; i < size; i++ {
		c.Set(i, i)
	}

	entries := make([]Entry[int, int], 0, size)
	for i := 0; i < size; i++ {
		// saving snapshots
		e, ok := c.Extension().GetEntry(i)
		if !ok {
			t.Fatalf("not found entry. key: %d", i)
		}
		if e.HasExpired() {
			t.Fatalf("entry should not be expired. key: %d", i)
		}
		entries = append(entries, e)
	}

	for i := 0; i < size; i++ {
		// checking expiration time
		if _, ok := c.Get(i); !ok {
			t.Fatalf("not found value. key: %d", i)
		}
	}

	time.Sleep(2 * defaultTTL)

	for i := 0; i < size; i++ {
		// checking expiration time
		// if Entry has been expired, GetEntry should always return ok = false.
		_, ok := c.Extension().GetEntry(i)
		if ok {
			t.Fatalf("entry found. key: %d", i)
		}
	}

	for _, e := range entries {
		if !e.HasExpired() {
			t.Fatalf("the snapshot should be expired. key: %d", e.Key())
		}
	}
}
```
`Entry` is a snapshot of a real entry and will not change in any way after creating it. For example, its expiration time is copied from the real entry. `TTL` and `HasExpired` are calculated dynamically, since these methods must also know the current time.
So this can cause problems if you update the expiration time (update the key-value pair), but I tried to warn as much as possible about this in the [comments](https://github.com/maypok86/otter/blob/main/entry.go#L23) and specifically added the `GetEntryQuietly` method, which has excellent speed and does not update eviction policies.
