### ISSUE TITLE
adding more than the maximum capacity limit returns a Boolean value

### ISSUE THREAD

**Issue by UallenQbit** [maypok86/otter#31]
#clarificationandmotivation

Use Set and SetWithTTL to return false if the Key setting exceeds the maximum capacity of NewCache and fails.

#Acceptance criteria

For example, if I use NewCache to set the maximum capacity to 3, and I set 4 Keys, the first three keys will return true if they do not exceed the maximum capacity limit, and the fourth key will return false if they exceed the maximum capacity limit.

**Comment by maypok86** [comment]
Hi, that's an interesting suggestion. A similar change is planned, largely because of this otter remains under development. But I intended to return a bool to show if an item was accepted for processing [here](https://github.com/maypok86/otter/blob/main/cache.go#L164) (maybe more conditions later).

There are a few problems with your proposal.
1. Not very clear on the meaning of bool depending on cache fullness. It seems that it will always be true some time after the application starts, since the cache already stores the maximum number of items and if a new item is inserted into it, it has to decide which item will be deleted.
2. It is simply impossible to implement it in this way, since otter interacts with the eviction policy using the eventual consistency model, i.e. the Set command does not have direct access to the eviction policy.

**Comment by maypok86** [comment]
So far I've only added returning a boolean value for items with too high a cost, but I'd like to know why you need the mechanics you suggest.

**Comment by maypok86** [comment]
@UallenQbit Unfortunately, there are two problems with this at once.
1. Otter supports cost-based eviction because of which the capacity may always be much larger than the number of elements in the hash table.
2. It's still unclear why anyone would want to do this.

**Comment by maypok86** [comment]
I really don't know how to satisfy this issue without a huge loss in performance (even leaving the convenience of the other users out of the discussion).
