### ISSUE TITLE
automatic permanent ttl

### ISSUE THREAD

**Issue by UallenQbit** [maypok86/otter#39]
# Clarification and motivation

Add SetWithTTL to automatically use permanent TTL when TTL is 0. People usually like to use 0ttl or -1TTL to represent permanent TTL. For example, Ristretto 0TTL is permanent TTL, and Redis -1TTL is permanent TTL.

# Acceptance criteria

The ttl passed in using the SetWithTTL function is less than 0 and is automatically set to permanent tt. This is also what Ristretto does in Redis.

I have initiated a merge request https://github.com/maypok86/otter/pull/38

**Comment by maypok86** [comment]
Hi, thanks for the interesting issue!

Actually, in ristretto it was done for development convenience, not user-friendliness. And in redis it's most likely the same, especially since even the official documentation doesn't say a word about it.

I have a suspicion that you need this behavior for some kind of wrapper over various caches. Perhaps then you should add an if with the behavior you need in it? Especially since you will probably need it anyway.

**Comment by maypok86** [comment]
Okay, I think we're done here.
