### ISSUE TITLE
Add save and restore to file

### ISSUE THREAD

**Issue by RJKeevil** [maypok86/otter#51]
# Clarification and motivation

Hello, i'm interested in testing the performance of your cache in my application.  Currently I use theine.  Only thing I can see that I am missing from the API is the ability to save and restore the cache from file, so warm restarts are possible (very important for my app).

# Acceptance criteria

Important that the file object is e.g. a generic io.ReadCloser, as we use afs (abstract file system) to use any cloud object store.

Thanks!

**Comment by maypok86** [comment]
Hi, you're not the first with such a request, which clearly shows the need for this feature, but there are a few nasty problems.

1. By design, otter was supposed to be responsible for in-memory caching and do it as best as possible. Interaction with files is unfortunately not included in this domain. But okay, we can make an exception.

2. Theine saves not only keys, values, ttls and costs, but also meta information about eviction policy. I'm not willing to allow this, because it obliges the library to guarantee that it will never change the structure of its eviction policy in the future, because changing it would cause very nasty errors when updating the library. And otter is extremely likely to make changes to the eviction policy.

3. Because of the previous two points, I was betting on the `Range` function, planning to just prompt users to save key-value pairs to a file themselves and load the cache from the file, but I'm not sure about this solution and am open to discussion.

**Comment by maypok86** [comment]
Basically, you can continue to use theine. It is written quite well. There are only a few things I don't like about it: 
- poor cost synchronization, which can lead to panics when using cost-based eviction
- high per entry memory overhead, which is somewhat hidden by the excellent implementation of count-min sketch (not important for the vast majority of applications). [The memory consumption analysis I wrote a while back](https://maypok86.github.io/otter/performance/memory-consumption/)

**Comment by maypok86** [comment]
And just for fun, why is cold start so scary to you?

**Comment by RJKeevil** [comment]
Hi @maypok86 , actually having the range function is all I need really, I missed that.  I just need the keys and values to be restorable, ttls and costs etc can be recreated.

For my app cold (re)starts can be problematic because I use the cache to store results of particularly expensive DB queries that can be eventually consistent in a highly concurrent system.  If all workers are simultaneously restarted without caches, the DB will have a masssive load spike which can hurt performance and stability.

So I think this request just becomes: perhaps it is worth having a convenience function that ranges over the cache to directly produce the file.  Your call really, i'm happy to do that on my side.

**Comment by maypok86** [comment]
I guess I won't add saving to the file for now after all. It seems better to let users do it the way they want.

Maybe it will be added, but only after otter closes all the problems with its domain. Which will be much later :)
