### ISSUE TITLE
Callback function for evict items

### ISSUE THREAD

**Issue by drslumpcoder** [maypok86/otter#63]
# Clarification and motivation

This is awesome lib. But if have callback function for evict items or [RemovalListener](https://github.com/Yiling-J/theine-go/blob/main/builder.go#L97), it is very useful for maintain or free memory of item value.

Thanks.

# Acceptance criteria

**Comment by maypok86** [comment]
Hi, okay, I'll include this in the next release along with #56. But I have to warn you, since otter does not use exclusive locks unlike other libraries, using `RemovalListener` to free up memory is a bad idea. Since when executing a function on this entry, you can get a panic due to access to the freed memory. I will most likely add the ability to specify a custom allocator in the builder, but this will be much later, since for this we need to maintain the reference counter very carefully.

**Comment by maypok86** [comment]
@drslumpcoder please take a look, is this api suitable for you?
```go
c, err := otter.MustBuilder[uint64, uint64](100).
		CollectStats().
		DeletionListener(func(key uint64, value uint64, cause DeletionCause) {
			// do something...
		}).
		Build()
```
A deletion listener can handle the following causes

- `Explicit` (the entry was manually deleted by the user)
- `Replaced` (the entry itself was not actually deleted, but its value was replaced by the user)
- `Size` (the entry was evicted due to size constraints)
- `Expired` (the entry's expiration timestamp has passed)

**Comment by drslumpcoder** [comment]
> suitable

Yes, this function is very suitable for me.
