### ISSUE TITLE
concurrent access slice

### ISSUE THREAD

**Issue by woodliu** [maypok86/otter#85]
In [internal/lossy/buffer.go](https://github.com/maypok86/otter/blob/main/internal/lossy/buffer.go), I think `func (b *Buffer[K, V]) Add(n node.Node[K, V]) *PolicyBuffers[K, V]` and `func (b *Buffer[K, V]) Free()` can be called at the same time, 
so when run`Add`( `pb.Returned = append(pb.Returned, b.nodeManager.FromPointer(v))`)  and `Free()` may concurrent access the same slice because there is no locker or `atomic.CompareAndSwapPointer`.

**Comment by maypok86** [comment]
`Free` is called separately because we need to know that the buffer has been processed by the eviction policy.

Not really, the role of lock is performed by [this](https://github.com/maypok86/otter/blob/main/internal/lossy/buffer.go#L93) cas operation. It ensures that only one thread will work with `Returned`.

**Comment by woodliu** [comment]
@maypok86 You are right! There is no chance for `Add` and `Free` to change the same `Returned`
