### ISSUE TITLE
[BUG] The capacity of cache not work

### ISSUE THREAD

**Issue by timandy** [maypok86/otter#88]
## Description

set capacity to 10, but the cache can store over 10 elements.

## To Reproduce

```go
cache, err := otter.MustBuilder[int, int](10). //set capacity to 10
		Cost(func(key int, value int) uint32 { return 1 }).
		WithTTL(time.Second).
		Build()
	if err != nil {
		panic(err)
	}

	// put 20(>10) items to cache
	for i := 0; i < 20; i++ {
		cache.Set(i, i)
	}

	cntCacheMiss := 0
	for i := 0; i < 20; i++ {
		value, ok := cache.Get(i)
		fmt.Println(value)
		if !ok {
			cntCacheMiss++
		}
	}
	assert.Equal(t, 10, cntCacheMiss) //fails
```
## Expected behavior

test pass

## Environment

- OS: windows 11
- go 1.20 amd64

## Additional context

github.com/maypok86/otter v1.2.1

**Comment by timandy** [comment]
@maypok86 Thanks for your quick answer, I have got it.

**Comment by ben-manes** [comment]
yeah, either you sequence writes by a fat lock with a strict bound, or you allow some slack to temporarily exceed it (to a threshold) to allow for better concurrency. You can shard the lock but then you lose capacity by the more shards you add trying to fix write performance. Since the deallocation is lazy anyway in a GC’d language, it doesn’t benefit you at all by being strict if the runtime is loose.
