### ISSUE TITLE
[BUG] The checkedAdd method will not return maxInt64 in case of overflow

### ISSUE THREAD

**Issue by tangwenqiang** [maypok86/otter#91]
## Description

The [checkedAdd](https://github.com/maypok86/otter/blob/e57f61b947ff2308dd2e02ee181cef634b8dfd66/stats.go#L83) will return (maxInt64 - 2) instead of maxInt64 as the comment saying.

(A possible fix could be:  `((naiveSum >> 63) ^ 1)`  =>  `int64((uint64(naiveSum)>>63)^1)`)

## To Reproduce

run this test:
```go
func TestCheckedAdd(t *testing.T) {
	var a, b int64
	a = math.MaxInt64
	b = 23
	
	fmt.Println(checkedAdd(a, b))  // output is: 9223372036854775805 
}
```

## Expected behavior
return maxInt64 when overflow.

**Comment by maypok86** [comment]
Hi, yeah, it looks like I made a mistake in two places at once.

It really should have been an unsigned shift. I tried to test the correctness of this function using `Ratio` but there was an incident with float64 rounding.

```go
hits := math.MaxInt64
requests := math.MaxInt64 - 2
result := float64(hits)/float64(requests)
fmt.Println(result)
```

Here the result will be exactly 1.0 :(

I'll probably add a fix to the v2.0 release because users are unlikely to be able to notice this bug.
