### ISSUE TITLE
[BUG] DeletionListener not triggering consistently

### ISSUE THREAD

**Issue by joaquinpf** [maypok86/otter#98]
## Description

It seems that DeletionListener doesn't always trigger for the explicit deletion scenario (through the Delete(key) function). While it seems like a bug, it could be me not using the feature correctly.

## To Reproduce

Using [this working test](https://github.com/maypok86/otter/blob/f2b403bcdc0200b7efd278e1c7127e9b72a6c399/cache_test.go#L232) as a base, simply modify the "size" to 100 (or other values), like so: 

```
func TestCache_Delete_Modified(t *testing.T) {
	size := 100
	var mutex sync.Mutex
	m := make(map[otter.DeletionCause]int)
	c, err := otter.MustBuilder[int, int](size).
		InitialCapacity(size).
		WithTTL(time.Hour).
		DeletionListener(func(key int, value int, cause otter.DeletionCause) {
			mutex.Lock()
			m[cause]++
			mutex.Unlock()
		}).
		Build()
	if err != nil {
		t.Fatalf("can not create builder: %v", err)
	}

	for i := 0; i < size; i++ {
		c.Set(i, i)
	}

	for i := 0; i < size; i++ {
		if !c.Has(i) {
			t.Fatalf("key should exists: %d", i)
		}
	}

	for i := 0; i < size; i++ {
		c.Delete(i)
	}

	for i := 0; i < size; i++ {
		if c.Has(i) {
			t.Fatalf("key should not exists: %d", i)
		}
	}

	time.Sleep(time.Second)

	mutex.Lock()
	defer mutex.Unlock()
	if len(m) != 1 || m[otter.Explicit] != size {
		t.Fatalf("cache was supposed to delete %d, but deleted %d entries", size, m[otter.Explicit])
	}
}
```

Which results in:
```
=== RUN   TestCache_Delete_Modified
    cache_test.go:198: cache was supposed to delete 100, but deleted 92 entries
--- FAIL: TestCache_Delete_Modified (5.01s)
```

Tracking 92 of the 100 entries

## Expected behavior

DeletionListener should be called for all explicitly deleted entries

## Environment

otter 1.2.1
go 1.22 

## Additional context

- Increasing the sleep time even to a large value like 30s doesn't seem to help. 
- Curiously, the test works for 256, 512, 1024, 2048 and so on, so I'm guessing it's related to the operation of some buffer?

**Comment by maypok86** [comment]
Hi. Yeah, this is because of the buffer that is used to apply operations to eviction and expiration policies ([some link](https://github.com/maypok86/otter/blob/main/internal/core/cache.go#L381)).

In real life, this shouldn't affect you very much. Maybe, except for various scenarios in which the `deletionListener` is used to close connections and an instant reaction to this is very important to you.

P.S. Too many issues are created for this behavior... I will have to try to abandon prefetching in favor of processing one entry at a time.

**Comment by hyzhangzhy** [comment]
Hello, author.

May I ask, if I'd like to use `DeletionListener` as a delay queue to call a delay function.

Is there any risk if i change the buffer size to 1? 
I think change to 1 will disable the buffer, so it will reaction instantly.

Maybe we can expose the buffer size?

**Comment by AllenZMC** [comment]
> Hello, author.
> 
> 
> 
> May I ask, if I'd like to use `DeletionListener` as a delay queue to call a delay function.
> 
> 
> 
> Is there any risk if i change the buffer size to 1? 
> 
> I think change to 1 will disable the buffer, so it will reaction instantly.
> 
> 
> 
> Maybe we can expose the buffer size, so we can change it outside?
> 
> 
> 
> 

@maypok86 I have the same question, hope you can reply soon.

**Comment by maypok86** [comment]
Hi, I tried to fix it and it seems to have worked. I will try to check again tomorrow and merge the pull request, but so far without publishing a new release.

**Comment by maypok86** [comment]
> Maybe we can expose the buffer size, so we can change it outside?

I don't think adding implementation specifics to the API is a good idea.

**Comment by hyzhangzhy** [comment]
@maypok86 
Hello author, I tried your code, but found an issue.
I use this code below. It sets a key with ttl=12, and open a loop to get the key every 3 seconds.
```go
func TestGetExpired(t *testing.T) {
	c, err := MustBuilder[string, string](1000000).
		CollectStats().
		DeletionListener(func(key string, value string, cause DeletionCause) {
			fmt.Println(cause)
		}).
		WithVariableTTL().
		Build()
	if err != nil {
		t.Fatal(err)
	}
	c.Set("test1", "123456", time.Duration(12)*time.Second)
	for i := 0; i < 5; i++ {
		c.Get("test1")
		time.Sleep(3 * time.Second)
	}
	select {}
}
```
Which result in:
```
=== RUN   TestGetExpired
Explicit
```
I think it should output expired instead of explicit. 
And after I read your code, it push a delete to the writebuffer in get.
![image](https://github.com/user-attachments/assets/879ebf11-7c36-4e57-86c0-e27d34608311)
I'd like to contribute, maybe i can add a new case here, to fix this issue?
![image](https://github.com/user-attachments/assets/5ffefe16-b920-4e2d-967f-da096809548c)

**Comment by hyzhangzhy** [comment]
> Oh, I totally forgot about this if. Yes, this should be enough, but it's worth adding `n.Die()` to stop various possibilities for race conditions. aka
> 
> ```go
> if n.HasExpired() {
>     n.Die()
>     c.writeBuffer.Push(newExpireTask(n))
>     c.stats.IncMisses()
>     return nil, false
> }
> ```

ok

**Comment by hyzhangzhy** [comment]
I open a PR.
https://github.com/maypok86/otter/pull/104

**Comment by maypok86** [comment]
I will publish a release with the latest changes in a few hours.

**Comment by maypok86** [comment]
The new release has been published
